---
title: Irving D. Hernández
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: nxdavid@oceanica.ufrj.br
description: General Manager of the Ocean Structures Laboratory NEO at the Federal
  University of Rio de Janeiro - COPPE, Brazil.
baseurl: ''
url: idavidhf.github.io
twitter_username: irvingdhf
github_username: idavidhf
theme: minima
plugins:
- jekyll-feed
